source 'https://rubygems.org'

ruby '2.6.3'

gem 'rails', '~> 6.0.0'
gem 'sqlite3', '~> 1.4'
gem 'puma', '~> 3.12'
gem 'bootsnap', '>= 1.4.2', require: false

group :development, :test do
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
end
